### ISSUE TITLE
📤 Aplicar clase `ampliar` y la definición a cada aparición de siglas 

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-vacs#10]
Ponerle las definiciones a las tipo *ampliar* a cada sigla:

Por ejemplo:
EVCNNA: 
- Ubicación en el código:
https://github.com/enflujo/imagina-vacs/blob/254e5f29e0c3e2d27b526a6932ad113432d998b2/src/pages/index.astro#L60C99-L60C105  Encuesta Nacional de Violencia contra Niños, Niñas y Adolescentes

ACES 
- ubicación en el código:
https://github.com/enflujo/imagina-vacs/blob/254e5f29e0c3e2d27b526a6932ad113432d998b2/src/pages/index.astro#L88C30-L88C57 : Adverse Childhood Experiences / Experiencias adversas en la infancia. 
- ubicación en la página: 
https://hyp.is/18W6mBdiEe6kaasAHecOcQ/imagina.uniandes.edu.co/especiales/vacs/proyecto2/

**Comment by 1cgonza** [comment]
No entiendo muy bien que significa en este caso "Aplicar clase".

**Comment by anattolia** [comment]
Creo que la idea es que cuando aparezcan siglas, pueda aparecer la definición con un hover o un click.

**Comment by 1cgonza** [comment]
> Creo que la idea es que cuando aparezcan siglas, pueda aparecer la definición con un hover o un click.

Ah entiendo, gracias!

**Comment by 1cgonza** [comment]
resuelto en [e961e12](https://github.com/enflujo/imagina-vacs/commit/e961e123bedffe90fb15bea7dbde8d0b2362c595)
