### ISSUE TITLE
🤓 1era reunión de revisión

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-vacs#12]
Cotejar apuntes sobre el diseño, el texto, las tablas y los pasos a seguir.

**Comment by anattolia** [comment]
👁️ 👁️ 
    -

¿Cuándo?

**Comment by Juliansintilde** [comment]
> 👁️ 👁️ __ ::: __ Jajajaj :)
> 
> ¿Cuándo?

yo había puesto este issue pensando en la que ya tuvimos tú y yo el viernes, jajaja. Si necesitamos una con Juan, o una segunda en cualquier caso, sería hacer otro Issue, creo jeje 😄
