### ISSUE TITLE
🗣 Gesto *testimonio*

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-vacs#16]
Implementar gesto de testimonios. 
Hacer que el texto escrito esté solo en la pantalla al hacer scroll. 
Sale del eje z: se agranda y pasa de invisible a completa visibilidad.
Al entrar en ese aparte de lectura, el fondo de color de la página cambia de color.

En este punto: 
https://hyp.is/JvXgIBdeEe6V57M959MkbA/imagina.uniandes.edu.co/especiales/vacs/proyecto1/

**Comment by 1cgonza** [comment]
resuelto en 03f7cffe55b26a32aad3ae73517539eeb3754a02
