### ISSUE TITLE
🔧 [VACS-2] Agregar clase a cada elemento de las historias

### ISSUE THREAD

**Issue by anattolia** [enflujo/imagina-vacs#2]
<p>Los tipos de elementos son:</p>
<ul>
<li><code>.narracion</code>: Texto general de la narración.</li>
<li><code>.grafica</code>: Visualización o imagen relacionada con datos. Puede contener datos en texto que se transforman a visualizaciones o algo así.</li>
<li><code>.destacado</code>: Frases resaltadas tipo artículo periodístico.</li>
<li><code>.escribiendo</code>: Textos conectores animados (quizás como si se fueran escribiendo).</li>
<li><code>.relato</code>: Citas, relatos en primera persona.</li>
</ul>

**Comment by 1cgonza** [comment]
El de `.escribiendo` quedó resuelto en 9b114973514cade8325dd2daac73f6083cba1742
