### ISSUE TITLE
✏️ Definir paleta de color general

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-vacs#21]

**Comment by Juliansintilde** [comment]
Ya están cargados los colores de las variales:
Esta es la guía, por si acaso.
![Mesa de trabajo 1 copia](https://github.com/enflujo/imagina-vacs/assets/42554838/dcb2aa32-ddcf-4092-b999-21c6c16c7d67)

**Comment by 1cgonza** [comment]
Pasado a https://github.com/enflujo/imagina-vacs/discussions/36
