### ISSUE TITLE
✏️ Definir tipografía general

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-vacs#22]

**Comment by Juliansintilde** [comment]
Ya están cargadas en el main.
Esta es la guía por si acas.
![Mesa de trabajo 1 copia 4](https://github.com/enflujo/imagina-vacs/assets/42554838/8d05d846-f0ec-4273-9769-647899e13883)

**Comment by 1cgonza** [comment]
Pasado a https://github.com/enflujo/imagina-vacs/discussions/35
