### ISSUE TITLE
✏️ Definir diagramación general 

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-vacs#23]

**Comment by Juliansintilde** [comment]
Esta es la propuesta general con una primera vista para celulares:
Queda en esta carpeta:
https://uniandes-my.sharepoint.com/:f:/g/personal/j_gonzalezj_uniandes_edu_co/EoTnFRt9YsdHs2T_YG4q1GcBZU017n3GMQh3NRPTh1irIA?e=4x9owQ

Los recursos:
https://uniandes-my.sharepoint.com/:f:/g/personal/j_gonzalezj_uniandes_edu_co/EjArBnpLhgpBj0-ZeIVf4cwB9NoViu6PtLx1Wf5y1MW7Uw?e=7TPUw1

Empieza solo el título y subtíulo, las nubes son elementos animados hacia el lado.

![0_index](https://github.com/enflujo/imagina-vacs/assets/42554838/347b3a56-b325-43c2-b19a-3a6d2d0d1a53)

Cuando se hace scroll hacia abajo, desaparece la flecha.
Conforme se hace scorll se van desapareciendo los elementos de título y subtítulo, que estarían con posición fija.
![1_index](https://github.com/enflujo/imagina-vacs/assets/42554838/83016bbb-6e6d-4e22-903c-4684fdd54c3e)

Queda la línea de color fija arriba separando del título:
![2_index](https://github.com/enflujo/imagina-vacs/assets/42554838/6aacb3d5-16ee-4681-b5bc-a8a07193f823)

![3_index](https://github.com/enflujo/imagina-vacs/assets/42554838/80b08e2b-ff7d-49c9-adba-72d191315c8a)

Esta sería la versión sencilla. Si no tenemos una gráfico, dibujo o algo que anticipe la infirmación, serían los tres uno debajo de otro.
![4_index_opcion1](https://github.com/enflujo/imagina-vacs/assets/42554838/48d14765-d85d-4cae-8e98-4175697005ed)

Si le incluímos esa gráfica entonces se retoma el scroll que arrastra primero los dos elementos amarillos los fija, y luego los demás.
![4_index_opcion2_1](https://github.com/enflujo/imagina-vacs/assets/42554838/a3838fad-f258-4764-b09b-3f8d74ca15a1)

![4_index_opcion2_2](https://github.com/enflujo/imagina-vacs/assets/42554838/5210ab62-b359-4687-b530-bfc91891475e)

![4_index_opcion2_3](https://github.com/enflujo/imagina-vacs/assets/42554838/3e4ade70-9d5e-4106-ae48-82a59f948671)

**Comment by 1cgonza** [comment]
Voy a pasar esto a la sección de `Discussions` para dejar lo que son ìssues` acá y las ideas o propuestas dejarlas visibles en discusiones https://github.com/enflujo/imagina-vacs/discussions/34
