### ISSUE TITLE
🖼️ Diseño de gráfica-tabla

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-vacs#32]
Diseñar la gráfica para la primera tala que vimos con @anattolia

**Comment by anattolia** [comment]
¿Esto sigue vigente? @Juliansintilde

**Comment by Juliansintilde** [comment]
@anattolia Creo que no. Creo que es la que ya diseñaron ustedes.

**Comment by Juliansintilde** [comment]
@anattolia . Creo que sí está pendiente. Y si no, podemos aprovechar este Issue para las gráficas pendientes del **paper 3**.
No han mandado datos. Podríamos decirles que si no los mandan esta semana, chao gráfica.

**Comment by Juliansintilde** [comment]
Ya se asignaron en los Issues #122 y #121

**Comment by Juliansintilde** [comment]
Ya se asignaron en los Issues https://github.com/enflujo/imagina-vacs/issues/122 y https://github.com/enflujo/imagina-vacs/issues/121
