### ISSUE TITLE
⤴️ Título fijo y transparente a media que se hace scroll

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-vacs#39]
Fijar el tìtulo para que al hacer scroll no suba y que la sección inmediatamente siguiente, pase por encima mientras se desvance:
<img src="https://github.com/enflujo/imagina-vacs/assets/42554838/bcc372fc-684e-4e80-b28a-2e3c06f29416" width="50%">
<img src="https://github.com/enflujo/imagina-vacs/assets/42554838/5449fb53-73d1-44ac-ba76-e9520ef4435e" width="50%">

**Comment by 1cgonza** [comment]
resuelto en 791db7f247b25f63fcbe1e47d30d9e72bbf629a4
