### ISSUE TITLE
☂️ Que la corniza quede fija pero tape los elementos  a medida que se hace scroll

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-vacs#41]
Con **corniza** me refiero a la barra de arriba que tiene las palabras "Menú" e "Historias" y los botones.

<img width="495" alt="image" src="https://github.com/enflujo/imagina-vacs/assets/42554838/e2f3f2da-ba1d-4202-9e23-a81675e3ab5e">

**Comment by 1cgonza** [comment]
resuelto en [1fe98bc](https://github.com/enflujo/imagina-vacs/commit/1fe98bc2bcd5dcf7de541b1098afed00ea9a76de)
