### ISSUE TITLE
😮‍💨 Diseñar íconos para gráfica de personitas

### ISSUE THREAD

**Issue by anattolia** [enflujo/imagina-vacs#94]
Diseñar los íconos para las gráficas de <personitas> ("X de cada Y personas)..

**Comment by Juliansintilde** [comment]
Hice varias versiones para tenerlas dispobles. Por ahora creo que me inclino por las casas, casa rellena amarilla para bien, casa rota rellena gris para mal.... pero las dejo aquí para que las miremos: https://uniandes-my.sharepoint.com/:f:/r/personal/j_gonzalezj_uniandes_edu_co/Documents/EnFlujo/Laboratorio%20EnFlujo/Proyectos/2023/Imagina%20-%20Fellows%20VACS/dise%C3%B1o/recursos/SVG?csf=1&web=1&e=7fodsU

![sol_tranqui_](https://github.com/enflujo/imagina-vacs/assets/42554838/8706fa74-6e4b-4d0b-9955-2a18797d1b32)
![sol_feliz_](https://github.com/enflujo/imagina-vacs/assets/42554838/d5c5aa75-366f-4ff9-ae83-0518c1e93d77)
![caratriste_](https://github.com/enflujo/imagina-vacs/assets/42554838/d9f93ecb-d656-4351-bc1c-3c3a6286c639)
![casa_contorno_rota_](https://github.com/enflujo/imagina-vacs/assets/42554838/cb5b929c-c0ff-4c9f-9cb2-56749afd78f3)
![casa_rellena_rota](https://github.com/enflujo/imagina-vacs/assets/42554838/0d9b5f20-ccd4-409e-a501-f840e5d3622d)
![casa_contorno_bien_](https://github.com/enflujo/imagina-vacs/assets/42554838/6ccc8f14-e70b-4caa-a6ea-e4f1b4f5760e)
![casa_rellena_bien_2](https://github.com/enflujo/imagina-vacs/assets/42554838/fd9942a2-58cb-4375-96cd-c58da207e1a0)
![sol](https://github.com/enflujo/imagina-vacs/assets/42554838/e56ce746-b14d-4135-9155-3dbcde15113c)
![nube](https://github.com/enflujo/imagina-vacs/assets/42554838/75877c0b-e4a6-4c35-8281-b775868abe14)
![nube_triste_2](https://github.com/enflujo/imagina-vacs/assets/42554838/b84d5992-3c1c-432c-8ab1-b4eedeb4b410)
![nube_triste](https://github.com/enflujo/imagina-vacs/assets/42554838/7163c9a3-bab6-4cce-939f-08b69369d3ce)
![casa_rellena_bien](https://github.com/enflujo/imagina-vacs/assets/42554838/d0d37d2f-bab7-465a-987c-292067d7a057)
![casa_contorno_bien](https://github.com/enflujo/imagina-vacs/assets/42554838/d7edd0e4-902d-4f23-b356-3ea9aed519a5)
![sol_tranqui](https://github.com/enflujo/imagina-vacs/assets/42554838/8110a77a-2dae-4bb0-8ac5-f6b2f714a01a)
![caratriste](https://github.com/enflujo/imagina-vacs/assets/42554838/6f8e42ff-5b91-48f2-a313-b7e373d6ff30)
![sol_feliz](https://github.com/enflujo/imagina-vacs/assets/42554838/62823a45-94d9-4294-98db-a4aea2497981)

**Comment by Juliansintilde** [comment]
@anattolia Si quieres avanzar con lo de celulares yo puedo implementar estos iconitos, ¿qué opinas?

**Comment by anattolia** [comment]
Hecho 🌞
